version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      frontend:
        ipv4_address: 10.10.20.100
      admin:

  web:
    image: python:3.11
    container_name: hotel_web
    working_dir: /app
    volumes:
      - ./web:/app
    command: bash -c "pip install -r requeriments.txt && python main.py"
    networks:
      frontend:
        ipv4_address: 10.10.20.1
      admin:

  pagos:
    image: python:3.11
    container_name: pagos_service
    working_dir: /pagos
    volumes:
      - ./pagos:/pagos
    command: python pagos.py
    networks:
      dmz:
        ipv4_address: 10.10.10.1
      admin:

  iot_termostato:
    image: python:3.11
    container_name: iot_termostato
    working_dir: /iot
    volumes:
      - ./iot:/iot
    command: python termostato.py
    networks:
      iot:
        ipv4_address: 10.10.30.2

  iot_sensor:
    image: python:3.11
    container_name: iot_sensor
    working_dir: /iot
    volumes:
      - ./iot:/iot
    command: python sensor.py
    networks:
      iot:
        ipv4_address: 10.10.30.3

  logs:
    image: python:3.11
    container_name: logs_service
    working_dir: /logs
    volumes:
      - ./logs:/logs
    command: python logs.py
    networks:
      admin:

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.20.0/24
  admin:
    driver: bridge
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  iot:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.30.0/24

volumes:
  db_data:
